markdown: redcarpet
name: Joining 18F
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: So you want to join 18F?
  url: index.html
  internal: true
- text: Who we are hiring
  url: who-we-are-hiring/
  internal: true
- text: How to apply
  url: how-to-apply/
  internal: true
- text: Interview process
  url: interview-process/
  internal: true
- text: Benefits
  url: benefits/
  internal: true
- text: Government pay grades explained
  url: pay-grades/
  internal: true
- text: Leave policies
  url: leave-policies/
  internal: true
- text: Conferences, training, and travel
  url: conferences-training-travel/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/joining-18f

# Collections
collections:
  positions:
    permalink: /positions/:title/
    output: true
  interviews:
    permalink: /interviews/:title/
    output: true

google_analytics_ua: UA-48605964-19

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
