baseurl: /joining-18f
markdown: redcarpet
name: Joining 18F
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: The Interview Process
  url: interview-process/
  internal: true
- text: Government Pay Grades Explained
  url: pay-grades/
  internal: true
- text: Benefits
  url: benefits/
  internal: true
- text: Leave Policies
  url: leave-policies/
  internal: true
- text: Conferences, Trainings, and Travel
  url: conferences-training-travel/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/joining-18f

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-48605964-19
